version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_bitrix
      MYSQL_USER: studentq
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: studentq
      PMA_PASSWORD: 1234
    ports:
      - '8080:80'
